"""Tests for f1/comparison (multi-driver F1 delta, todo.md M3).

Runs offline on the multi-driver synthetic Monza fixture generated by
tools/fixture_f1.py (one bridged contract CSV per driver).
"""

from __future__ import annotations

import os

import pandas as pd
import pytest

from f1 import comparison
from pitmind.config import Config

DATA = os.path.join(os.path.dirname(__file__), "..", "data")
DRIVERS = ["VER", "LEC", "SAI"]


@pytest.fixture(scope="module")
def sessions():
    return {
        code: pd.read_csv(os.path.join(DATA, f"f1_monza_driver_{code}.csv"))
        for code in DRIVERS
    }


@pytest.fixture(scope="module")
def cfg():
    return Config.from_file()


def test_driver_corner_table_shape(sessions, cfg):
    tbl = comparison.driver_corner_table(sessions["VER"], cfg)
    assert {"corner", "name", "n_laps", "mean_corner_time_s",
            "total_loss_s", "top_mistake", "top_delta_value"} <= set(tbl.columns)
    assert len(tbl) >= 1
    assert (tbl["total_loss_s"] >= 0).all()
    # Monza -> ~7 corners
    assert abs(len(tbl) - 7) <= 1


def test_compare_drivers_returns_all_non_reference(sessions, cfg):
    comps = comparison.compare_drivers(sessions, cfg, reference_driver="SAI")
    assert {c.driver for c in comps} == {"VER", "LEC"}
    assert all(c.reference_driver == "SAI" for c in comps)
    # one delta per corner per driver
    n_corners = len(comparison.driver_corner_table(sessions["SAI"], cfg))
    assert all(len(c.corner_deltas) == n_corners for c in comps)


def test_compare_drivers_auto_picks_reference(sessions, cfg):
    comps = comparison.compare_drivers(sessions, cfg)  # reference auto-selected
    assert len(comps) == len(DRIVERS) - 1
    # reference excludes itself, and is one of the drivers
    refs = {c.reference_driver for c in comps}
    assert len(refs) == 1
    assert refs <= set(DRIVERS)
    assert all(c.driver != c.reference_driver for c in comps)


def test_delta_sign_and_root_cause(sessions, cfg):
    comps = comparison.compare_drivers(sessions, cfg, reference_driver="SAI")
    for comp in comps:
        for d in comp.corner_deltas:
            # delta = driver_loss - ref_loss
            assert d.delta_s == pytest.approx(d.driver_corner_loss_s - d.ref_corner_loss_s, abs=1e-3)
            # root cause is a human-readable phrase or None
            assert d.root_cause is None or isinstance(d.root_cause, str)
        # worst_corners sorted by delta desc
        worst = comp.worst_corners(3)
        deltas = [w.delta_s for w in worst]
        assert deltas == sorted(deltas, reverse=True)


def test_comparison_to_dataframe(sessions, cfg):
    comps = comparison.compare_drivers(sessions, cfg, reference_driver="LEC")
    df = comparison.comparison_to_dataframe(comps)
    assert {"driver", "vs", "corner", "delta_s", "root_cause"} <= set(df.columns)
    assert len(df) == sum(len(c.corner_deltas) for c in comps)


def test_phrase_delta_readable(sessions, cfg):
    comps = comparison.compare_drivers(sessions, cfg, reference_driver="LEC")
    for comp in comps:
        text = comparison.phrase_delta(comp)
        assert comp.driver in text and comp.reference_driver in text
        assert "s to" in text or "s than" in text or " loses " in text or " gains " in text


def test_requires_at_least_two_drivers(sessions, cfg):
    with pytest.raises(ValueError):
        comparison.compare_drivers({"VER": sessions["VER"]}, cfg)


# ------------------------------------------------------------- sector (M5/C3)
def test_compare_sectors_returns_non_reference_driver_sectors(sessions, cfg):
    deltas = comparison.compare_sectors(sessions, cfg, reference_driver="SAI")
    assert {s.driver for s in deltas} == {"VER", "LEC"}
    for s in deltas:
        assert s.sector in (1, 2, 3)
        assert s.delta_s == pytest.approx(s.driver_sector_loss_s - s.ref_sector_loss_s, abs=1e-3)
        assert s.n_corners >= 0


def test_compare_sectors_all_three_sectors_present(sessions, cfg):
    deltas = comparison.compare_sectors(sessions, cfg, reference_driver="SAI")
    for driver in {"VER", "LEC"}:
        secs = {s.sector for s in deltas if s.driver == driver}
        assert secs == {1, 2, 3}


def test_sector_corner_assignment_uses_lap_order():
    assert comparison._corner_to_sector(0, 9) == 1
    assert comparison._corner_to_sector(4, 9) == 2   # floor((4.5)/9*3)+1 = floor(1.5)+1=2
    assert comparison._corner_to_sector(8, 9) == 3
    assert comparison._corner_to_sector(0, 0) == 1   # degenerate guard


def test_sector_comparison_to_dataframe(sessions, cfg):
    deltas = comparison.compare_sectors(sessions, cfg, reference_driver="LEC")
    df = comparison.sector_comparison_to_dataframe(deltas)
    assert {"driver", "sector", "delta_s", "driver_loss_s", "ref_loss_s", "n_corners"} <= set(df.columns)
    assert df["sector"].isin(["S1", "S2", "S3"]).all()


def test_phrase_sector_delta_readable(sessions, cfg):
    deltas = comparison.compare_sectors(sessions, cfg, reference_driver="LEC")
    text = comparison.phrase_sector_delta(deltas, "VER")
    assert "VER" in text and "sector" in text.lower()
    assert "S" in text

